name: Django CI workflow

on:
  push:
    branches: [ "main"]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    needs: [docker-build]
    steps:
      - name: check code
        uses: actions/checkout@v4
      
      - name: run django tests
        run: |
          pip install pipenv
          pipenv install --system
          python manage.py makemigrations
          python manage.py migrate
          python manage.py test
        