name: Django Workflow

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
   build:

    runs-on: ubuntu-latest
    strategy:  
      max_parallel: 4
      matrix:
        python-version: [3.8, 3.10, 3.12]

    steps:
    - uses: actions/checkout@v4
    - name: Setup python ${{ matrix.python-version }}
      uses: actions/checkout@v3
      with: 
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        pip install pipenv
        pipenv sync
    - name: run tests
      run: |
        python manage.py test    